### ISSUE TITLE
Got error when trying to install `venvgit2` inside of virtualenv in CircleCI

### ISSUE THREAD

**Issue by ozooxo** [uniphil/venvgit2#24] opened 2019-07-12 11:22 UTC
Here is my failing test: https://circleci.com/gh/gitenter/gitenter/975?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

Error:

```
  Failed building wheel for venvgit2
  Running setup.py clean for venvgit2
  Running setup.py bdist_wheel for pycparser ... - \ | done
  Stored in directory: /home/circleci/.cache/pip/wheels/f2/9a/90/de94f8556265ddc9d9c8b271b0f63e57b26fb1d67a45564511
Successfully built pycparser
Failed to build venvgit2
Installing collected packages: attrs, zipp, importlib-metadata, pluggy, pyparsing, six, packaging, py, more-itertools, wcwidth, atomicwrites, pytest, urllib3, selenium, pycparser, cffi, venvgit2
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 345, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 316, in clobber
    ensure_dir(destdir)
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 83, in ensure_dir
    os.makedirs(path)
  File "/usr/local/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.6/site-packages/attr'
```

execution:

https://github.com/gitenter/gitenter/blob/699afa2e3f355ab05822cd560d9d770e912757bd/.circleci/config.yml#L366-L371

https://github.com/gitenter/gitenter/blob/699afa2e3f355ab05822cd560d9d770e912757bd/selenium-test/pip-requirements.txt#L3

**Comment by uniphil** [comment] 2021-04-05 23:12
hey @ozooxo 

i realize this is literally years late, but... if you're still having trouble i think the problem is with the lines

```yaml
      - run: cd selenium-test && . venv/bin/activate
      - run: cd selenium-test && pip install -r pip-requirements.txt
      - run: cd selenium-test && pytest tests/authorization_test.py
      - run: cd selenium-test && deactivate
```

in your [`gitenter/.circleci/config.yml`](https://github.com/gitenter/gitenter/blob/699afa2e3f355ab05822cd560d9d770e912757bd/.circleci/config.yml#L368-L371).

The activated virtual environment doesn't persist between `run` commands, so it would probably need to be something like

```yaml
- run:
  command: |
    cd selenium-test && \
    . venv/bin/activate && \
    pip install -r pip-requirements.txt && \
    [etc.]
```

i'm going to close this issue, but on the wild off-chance that this is still relevant to you, please feel free to reopen :)

**Closed by uniphil** 2021-04-05 23:12 UTC
